### ISSUE TITLE
Bad arm compile

### ISSUE THREAD

**Issue by joeland1** [Simple-Software-Solutions/SSS-Core#1]
No depends for arm version. Compiling with depends in rn.

sudo apt-get install software-properties-common
sudo add-apt-repository ppa:bitcoin/bitcoin
sudo apt install libgmp-dev
sudo apt install libevent-dev libboost-all-dev
sudo apt install build-essential libtool bsdmainutils autotools-dev autoconf pkg-config automake python3
sudo apt-get install libminiupnpc-dev
sudo apt-get install libzmq3-dev
sudo apt-get install libqt5gui5 libqt5core5a libqt5dbus5 qttools5-dev qttools5-dev-tools libprotobuf-dev protobuf-compiler
sudo apt-get install libqrencode-dev
apt install libssl1.0-dev
sudo apt install libssl1.0-dev

**Comment by Nugetzrul3** [comment]
What error are you getting?

**Comment by joeland1** [comment]
just doesnt want to compile with the dependencies
you will need to install dependencies seperate

**Comment by joeland1** [comment]
fixed
